-- +goose Up
BEGIN;

CREATE TABLE IF NOT EXISTS account.group_invite (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id varchar(32) REFERENCES travel.vacation_group(id) NOT NULL,
  token text UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  max_uses integer NOT NULL,
  used_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL,
  updated_by text NOT NULL
);

COMMIT;

-- +goose Down
BEGIN;

DROP TABLE IF EXISTS account.group_invite;

COMMIT;
