-- +goose Up
BEGIN;

CREATE SCHEMA IF NOT EXISTS account;
GRANT USAGE ON SCHEMA account TO vincadrn;

-- public.user_table
CREATE TABLE IF NOT EXISTS account.user_account (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE account.user_account TO vincadrn;

CREATE SCHEMA IF NOT EXISTS travel;
GRANT USAGE ON SCHEMA travel TO vincadrn;

-- public.group_table
CREATE TABLE IF NOT EXISTS travel.vacation_group (
  id varchar(32) PRIMARY KEY,
  name varchar(127) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE travel.vacation_group TO vincadrn;

-- public.groupuser
-- join table of travel.vacation_group and account.user_account
CREATE TYPE travel.user_role AS ENUM ('admin', 'member');
CREATE TABLE IF NOT EXISTS travel.user_vacation_group (
  user_id integer REFERENCES account.user_account (id),
  group_id varchar(32) REFERENCES travel.vacation_group (id),
  role travel.user_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (user_id, group_id)
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE travel.user_vacation_group TO vincadrn;

-- public.vacation
CREATE TABLE IF NOT EXISTS travel.vacation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget numeric(15,2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE travel.vacation TO vincadrn;

-- public.groupvacation
-- join table of travel.vacation and travel.vacation_group
CREATE TABLE IF NOT EXISTS travel.vacation_vacation_group (
  vacation_id integer REFERENCES travel.vacation (id),
  group_id varchar(32) REFERENCES travel.vacation_group (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (vacation_id, group_id)
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE travel.vacation_vacation_group TO vincadrn;

-- public.itinerary
CREATE TABLE IF NOT EXISTS travel.itinerary (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vacation_id integer REFERENCES travel.vacation (id),
  date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE travel.itinerary TO vincadrn;

-- public.list_itinerary
CREATE TABLE IF NOT EXISTS travel.itinerary_list (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id integer REFERENCES travel.itinerary (id),
  activity text NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE travel.itinerary_list TO vincadrn;

COMMIT;

-- +goose Down
BEGIN;
DROP SCHEMA account CASCADE;
DROP SCHEMA travel CASCADE;
COMMIT;
