server:
  host: localhost
  port: 8080
client:
  host: tvlknika-development.vincadrn.com
  port: 443
secretKeeper: local
cors:
  allowedOrigins:
    - 'http://localhost:5173'
    - 'https://tvlknika-development.vincadrn.com'
